###
POST http://localhost:3000/api/inventory/create
Content-Type: application/json

{
  "name": "new old test widget",
  "qty": 42,
  "shortdesc": "a widget for testing db",
  "longdesc": "a mock data throwaway that can be deleted at will",
  "city": "Tulsa"
}