PATCH http://localhost:3000/api/inventory/update
Content-Type: application/json

{
  "id": 5,
  "shortdesc": "did i null everything else?"
}

###
PATCH http://localhost:3000/api/inventory/update/1
Content-Type: application/json

{
  "qty": 9000
}

###
PATCH http://localhost:3000/api/inventory/update/1
Content-Type: application/json

{
  "shortdesc": "updated description",
  "longdesc": "a mock data throwaway that can be deleted at will",
  "city": "Tulsa"
}